-- Unified Supabase Schema for Antigravity Project
-- Includes: locations (from MariaDB) and crowd_records (from Supabase Setup)

-- 1. Create Enums for Locations
DO $$ BEGIN
    CREATE TYPE location_type AS ENUM ('CITY', 'PLANET', 'PLACE', 'ISLAND', 'COUNTRY', 'MOON');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. Create Locations Table (Transformed from MariaDB)
CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT,
    name VARCHAR(50) NOT NULL UNIQUE,
    picture VARCHAR(255),
    type location_type NOT NULL
);

-- 3. Create Crowd Records Table (from local setup)
CREATE TABLE IF NOT EXISTS crowd_records (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  session_id TEXT NOT NULL,
  username TEXT NOT NULL,
  location TEXT,
  person_count INTEGER DEFAULT 0,
  vehicle_count INTEGER DEFAULT 0,
  recorded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Indexes
CREATE INDEX IF NOT EXISTS idx_crowd_records_session ON crowd_records(session_id);

-- 5. Enable Realtime
-- Note: Realtime might already be enabled for the publication. 
-- We try to add tables to the 'supabase_realtime' publication.
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'crowd_records') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE crowd_records;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname = 'supabase_realtime' AND tablename = 'locations') THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE locations;
  END IF;
EXCEPTION
  WHEN others THEN 
    -- Publication might not exist yet, which is fine in some fresh projects
    NULL;
END $$;

-- 6. Insert Initial Location Data
INSERT INTO locations(name, description, picture, type)
VALUES 
('Gotham City', 'An American city rife with corruption and crime, the home of its iconic protector Batman.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/gotham_city.jpg', 'CITY'),
('Earth', 'Earth, our home planet, is the only place we know of so far that is inhabited by living things.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/earth.jpg', 'PLANET'),
('Krypton', 'An ancient world, Krypton was home to advanced civilization known as Kryptonians.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/krypton.jpg', 'PLANET'),
('Metropolis', 'Metropolis is depicted as being one of the largest and wealthiest cities in the world.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/metropolis.jpg', 'CITY'),
('Alkali Lake', 'Alkali Lake is the location where the secret Weapon X facility run by Colonel Striker was located.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/Alkali_Lake.jpg', 'PLACE'),
('Asgard', 'One of the nine realms that serve as home of the Norse god superheros.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/Asgard.jpg', 'PLACE'),
('The Savage Land', 'Located in Antarctica, it is a hidden prehistoric jungle inhabited by dinosaurs and primitive tribes.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/Savage_Land.jpg', 'PLACE'),
('Sakaar', 'A world located in a distant galaxy. Sakaar is a harsh and violent planet.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/Sakaar.jpg', 'PLANET'),
('The Death Star', 'Moon-sized space station with the ability to destroy an entire planet.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/Death_Star.png', 'PLACE'),
('Fortress of Solitude', 'Clark Kent sanctuary in the Arctic.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/Fortress_of_Solitude.jpg', 'PLACE'),
('Atlantis', 'An ancient underwater city, home to the Atlanteans.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/Atlantis.jpg', 'CITY'),
('Genosha', 'An island nation located off the east coast of Africa.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/Genosha.jpg', 'ISLAND'),
('Hoth', 'Ice planet located in the Outer Rim Territories.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/hoth.png', 'PLANET'),
('Endor', 'Forested moon orbiting the gas giant planet of Endor.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/endor.jpg', 'MOON'),
('Coruscant', 'City-covered planet at the heart of the galaxy.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/coruscant.png', 'PLANET'),
('Tatooine', 'Desert planet located in the Outer Rim Territories.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/tatooine.jpg', 'PLANET'),
('Neverwinter', 'City situated on the Sword Coast of the Forgotten Realms.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/neverwinter.jpg', 'CITY'),
('Baldur''s Gate', 'Coastal city on the Sword Coast, part of the Forgotten Realms.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/baldurs_gate.png', 'CITY'),
('Greyhawk', 'One of the earliest and most iconic campaign settings for D&D.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/greyhawkcity.jpg', 'CITY'),
('Tyr', 'Located in the Tablelands, Tyr is one of the city-states in the harsh world of Athas.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/tyr.jpg', 'CITY'),
('Tarantia', 'Capital city of the kingdom of Aquilonia in the Hyborian Age.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/tarantia.jpg', 'CITY'),
('Aquilonia', 'Powerful kingdom in the Hyborian Age and one of Conan''s most significant conquests.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/aquilonia.png', 'COUNTRY'),
('Cimmeria', 'Northern barbarian homeland in the Hyborian Age.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/cimmeria.png', 'COUNTRY'),
('Asteroid M', 'Created by Magneto, it was a haven for mutants.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/asteroid_m.png', 'PLANET'),
('Avalon', 'Island located in the Atlantic Ocean.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/avalon.png', 'ISLAND'),
('Monster Island (Kaiju Island)', 'Remote island in the Pacific Ocean inhabited by giant monsters.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/monster_island.jpg', 'ISLAND'),
('Madripoor', 'Fictional island nation located in Southeast Asia.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/madripoor.png', 'ISLAND'),
('K''un-Zi', 'One of the Seven Capital Cities of Heaven.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/kunzi.png', 'CITY'),
('K''un-Lun', 'Mystical, otherworldly city that exists on Earth once every decade.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/kunlun.png', 'CITY'),
('Latveria', 'European country ruled by Doctor Doom.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/latveria.jpg', 'COUNTRY'),
('Wakanda', 'Hidden African nation known for its reserves of Vibranium.', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/locations/wakanda.png', 'COUNTRY')
ON CONFLICT (name) DO NOTHING;
