
INSERT INTO public.monuments (title, description, location, state, category, latitude, longitude, is_featured, facts, distance_from_berhampur, region) VALUES

-- BERHAMPUR / GANJAM AREA MONUMENTS (50+ places)
('Tara Tarini Temple', 'One of the four major Adi Shakti Peethas in India, Tara Tarini Temple sits atop Kumari Hills near the Rushikulya River. The twin goddesses Tara and Tarini are worshipped here, drawing millions of devotees annually. The temple offers breathtaking panoramic views of the lush green valleys and the winding Rushikulya River below. During Chaitra month, a grand fair attracts visitors from across Odisha.', 'Purushottampur, Ganjam, Odisha', 'Odisha', 'Temple', 19.4750, 84.8975, true, ARRAY['One of four Adi Shakti Peethas in India','Twin goddesses Tara and Tarini are worshipped','Located atop Kumari Hills at 708 feet elevation','Annual Chaitra Mela draws over 1 lakh devotees','Connected to Tantric Buddhist traditions'], '30 km', 'berhampur'),

('Gopalpur-on-Sea Beach', 'A pristine and serene beach town that was once a bustling seaport for maritime trade with Southeast Asia. Gopalpur Beach features golden sands stretching for kilometers, with gentle waves perfect for swimming. The old lighthouse stands as a testament to its trading past. The beach is famous for its spectacular sunrises and the annual Olive Ridley turtle nesting season.', 'Gopalpur, Ganjam, Odisha', 'Odisha', 'Beach', 19.2584, 84.9052, true, ARRAY['Former major seaport for Southeast Asian trade','Home to an old colonial-era lighthouse','Olive Ridley turtles nest here annually','Known for spectacular sunrise views','One of the cleanest beaches in Odisha'], '16 km', 'berhampur'),

('Jaugada Fort & Ashoka Rock Edict', 'An ancient fortified site where Emperor Ashoka''s famous rock edicts were discovered, dating back to the 3rd century BCE. The edicts contain Ashoka''s messages of Dhamma (righteousness) and non-violence. The fort ruins include massive stone walls, bastions, and a moat. Excavations have revealed artifacts from the Mauryan period, making it one of the most important archaeological sites in eastern India.', 'Jaugada, Purushottampur, Ganjam, Odisha', 'Odisha', 'Fort', 19.5167, 84.7833, true, ARRAY['Contains Emperor Ashoka''s rock edicts from 3rd century BCE','One of the most important Mauryan archaeological sites in eastern India','Massive stone fortification walls still visible','Artifacts from multiple historical periods found','Mentioned in ancient texts as Samapa'], '30 km', 'berhampur'),

('Bhairabi Temple', 'An ancient temple dedicated to Goddess Bhairabi, a fierce form of Shakti. Located in the heart of Berhampur city, this temple is one of the most revered religious sites in southern Odisha. The temple architecture showcases traditional Kalinga style with intricate carvings. During Durga Puja and Navratri, the temple comes alive with elaborate celebrations and cultural programs.', 'Berhampur, Ganjam, Odisha', 'Odisha', 'Temple', 19.3149, 84.7941, true, ARRAY['One of the most revered temples in southern Odisha','Features traditional Kalinga architectural style','Major celebrations during Durga Puja and Navratri','Located in the heart of Berhampur city','Ancient temple with centuries of worship history'], '0 km', 'berhampur'),

('Taptapani Hot Springs', 'A natural hot water spring nestled in the Eastern Ghats at an altitude of 500 meters. The sulphur-rich water maintains a constant temperature of about 56°C and is believed to have medicinal properties for skin diseases and joint pain. Surrounded by dense forests, Taptapani is also home to a wildlife sanctuary with diverse flora and fauna including elephants and deer.', 'Taptapani, Ganjam, Odisha', 'Odisha', 'Natural Wonder', 19.4358, 84.3697, true, ARRAY['Hot spring water maintains constant 56°C temperature','Sulphur-rich water believed to cure skin diseases','Located at 500 meters altitude in Eastern Ghats','Adjacent wildlife sanctuary with elephants and deer','One of the few natural hot springs in Odisha'], '51 km', 'berhampur'),

('Chilika Lake (Rambha)', 'Asia''s largest brackish water lagoon, Chilika Lake near Rambha offers stunning natural beauty. The Rambha side is famous for its scenic boat rides, migratory bird watching (over 160 species), and Irrawaddy dolphin sightings. Nalabana Bird Sanctuary within the lake is a paradise for ornithologists. The lake supports a rich ecosystem with over 225 fish species and is a Ramsar Wetland of International Importance.', 'Rambha, Ganjam, Odisha', 'Odisha', 'Lake', 19.5167, 85.1000, true, ARRAY['Asia''s largest brackish water lagoon','Over 160 migratory bird species visit annually','Home to endangered Irrawaddy dolphins','Ramsar Wetland of International Importance','Supports over 225 species of fish'], '50 km', 'berhampur'),

('Narayani Temple', 'A prominent Hindu temple dedicated to Goddess Narayani situated in the Ganjam district. The temple is known for its vibrant festivثals and spiritual significance. Devotees believe that prayers offered here are especially powerful for removing obstacles and bringing prosperity. The temple complex includes beautiful gardens and meditation spaces.', 'Berhampur, Ganjam, Odisha', 'Odisha', 'Temple', 19.3200, 84.7900, false, ARRAY['Dedicated to Goddess Narayani','Popular for removing obstacles and bringing prosperity','Vibrant festival celebrations throughout the year','Beautiful temple gardens and meditation areas','Important pilgrimage site for southern Odisha'], '2 km', 'berhampur'),

('Aryapalli Beach', 'A hidden gem among Odisha''s coastline, Aryapalli Beach offers untouched golden sands and crystal-clear waters. Less commercialized than other beaches, it provides a peaceful retreat with stunning natural beauty. The beach is famous for its dramatic rock formations, tide pools teeming with marine life, and spectacular sunset views over the Bay of Bengal.', 'Aryapalli, Ganjam, Odisha', 'Odisha', 'Beach', 19.2800, 84.9200, false, ARRAY['One of the most pristine beaches in Odisha','Famous for dramatic rock formations and tide pools','Spectacular sunset views over Bay of Bengal','Less commercialized and peaceful retreat','Rich marine life visible in shallow waters'], '22 km', 'berhampur'),

('Rushikulya River Mouth', 'The Rushikulya River mouth is one of the three mass nesting sites of Olive Ridley sea turtles in India. Every year between January and March, hundreds of thousands of turtles arrive for nesting in a spectacular natural phenomenon called Arribada. The riverbank also offers serene picnic spots, mangrove forests, and excellent birdwatching opportunities.', 'Rushikulya, Ganjam, Odisha', 'Odisha', 'Natural Wonder', 19.3700, 85.0600, true, ARRAY['One of three mass Olive Ridley turtle nesting sites in India','Hundreds of thousands of turtles arrive during Arribada','Best viewing between January and March','Mangrove forests along the riverbank','Important ecological conservation zone'], '35 km', 'berhampur'),

('Potagarh Fort', 'A historical fort built during the Bhoi dynasty period, Potagarh Fort served as a strategic military outpost. The ruins include massive laterite walls, watchtowers, and remnants of royal quarters. The fort sits on elevated ground offering commanding views of the surrounding countryside. Local legends speak of hidden tunnels connecting it to nearby temples.', 'Potagarh, Ganjam, Odisha', 'Odisha', 'Fort', 19.3500, 84.9100, false, ARRAY['Built during the Bhoi dynasty period','Massive laterite walls still standing','Strategic military outpost with watchtowers','Legends of hidden tunnels to nearby temples','Panoramic views of surrounding countryside'], '12 km', 'berhampur'),

('Nirmaljhar Waterfall', 'A beautiful seasonal waterfall located in the Eastern Ghats near Aska. The waterfall cascades over multiple levels of rock formations, creating natural pools perfect for bathing. Surrounded by dense deciduous forest, the area is rich in biodiversity. A small Shiva temple near the waterfall adds spiritual significance to this natural wonder. Best visited during monsoon and post-monsoon seasons.', 'Aska, Ganjam, Odisha', 'Odisha', 'Waterfall', 19.5300, 84.5800, false, ARRAY['Multi-level cascade creating natural bathing pools','Surrounded by dense deciduous forest','Small Shiva temple adjacent to the waterfall','Best visited during and after monsoon season','Rich biodiversity in surrounding Eastern Ghats'], '40 km', 'berhampur'),

('Budhakhol Caves & Waterfalls', 'A stunning natural formation featuring ancient rock-cut caves alongside seasonal waterfalls in a pristine forest setting. The caves show evidence of habitation dating back thousands of years. The area is a popular trekking destination with well-marked trails through dense forest. During monsoon, the waterfall transforms into a magnificent cascade surrounded by lush greenery.', 'Budhakhol, Ganjam, Odisha', 'Odisha', 'Cave', 19.5800, 84.5200, false, ARRAY['Ancient rock-cut caves with evidence of early habitation','Stunning seasonal waterfall in pristine forest','Popular trekking destination with marked trails','Spectacular during monsoon season','Rich biodiversity in surrounding forest area'], '55 km', 'berhampur'),

('Mahuri Kalua Temple', 'An ancient Shaivite temple located atop a hill, offering panoramic views of the Ganjam countryside. The temple is dedicated to Lord Shiva and is particularly revered during Maha Shivaratri. The climb to the temple through forested hillside is itself a spiritual journey. Ancient stone inscriptions found here provide valuable historical insights.', 'Mahuri Kalua, Ganjam, Odisha', 'Odisha', 'Temple', 19.4100, 84.7500, false, ARRAY['Ancient Shaivite temple atop a scenic hill','Panoramic views of Ganjam countryside','Major celebrations during Maha Shivaratri','Ancient stone inscriptions with historical significance','Forested hillside climb adds to spiritual experience'], '18 km', 'berhampur'),

('Tampara Lake', 'A freshwater lake surrounded by lush greenery and hills, Tampara Lake is one of the most serene natural attractions near Berhampur. The lake is ideal for boating, fishing, and picnicking. It supports diverse aquatic life and attracts numerous migratory birds during winter. The surrounding area features walking trails and viewpoints perfect for nature photography.', 'Tampara, Ganjam, Odisha', 'Odisha', 'Lake', 19.3800, 84.7200, false, ARRAY['Beautiful freshwater lake surrounded by hills','Popular for boating, fishing, and picnics','Migratory birds visit during winter months','Walking trails and viewpoints for nature photography','One of the most serene spots near Berhampur'], '25 km', 'berhampur'),

('Dhabaleswar Temple', 'A revered Shiva temple located on a hilltop in Ganjam district, known for its ancient architecture and spiritual ambiance. The temple attracts devotees throughout the year and is especially crowded during Shravan month. The stone carvings on the temple walls depict scenes from Hindu mythology and are fine examples of Odisha''s temple art tradition.', 'Ganjam, Odisha', 'Odisha', 'Temple', 19.3600, 84.7800, false, ARRAY['Ancient Shiva temple with traditional architecture','Fine stone carvings depicting Hindu mythology','Especially popular during Shravan month','Hilltop location with spiritual ambiance','Example of Odisha temple art tradition'], '15 km', 'berhampur'),

('Mahodadhi Nagar Beach', 'A clean and well-maintained beach area in the Berhampur-Gopalpur stretch, Mahodadhi Nagar offers a relaxed coastal experience. The beach features soft sands, gentle waves, and coconut palm groves. Local fishermen can be seen with traditional boats, adding to the coastal charm. Street food stalls along the beach road serve fresh seafood and local delicacies.', 'Gopalpur Road, Ganjam, Odisha', 'Odisha', 'Beach', 19.2700, 84.8900, false, ARRAY['Clean and well-maintained beach','Coconut palm groves along the shore','Traditional fishing boats add coastal charm','Fresh seafood available at beach stalls','Relaxed atmosphere away from crowds'], '14 km', 'berhampur'),

('Biranchi Narayan Temple', 'One of the oldest and most significant temples in the Ganjam region, dedicated to Lord Vishnu in his Narayan form. The temple showcases excellent Kalinga architecture with ornate carvings of celestial beings and mythological narratives. The annual Rath Yatra here is celebrated with great fervor. Historical records date the temple to the 9th century.', 'Buguda, Ganjam, Odisha', 'Odisha', 'Temple', 19.6200, 84.7900, false, ARRAY['One of the oldest temples in Ganjam region','Excellent Kalinga architecture with ornate carvings','Dating back to the 9th century','Annual Rath Yatra celebrated with great fervor','Dedicated to Lord Vishnu as Narayan'], '35 km', 'berhampur'),

('Seranga Fort', 'A medieval fort that served as the seat of the Seranga chieftains who ruled parts of southern Odisha. The fort complex includes ruins of palaces, temples, granaries, and defensive walls. The architecture reflects a blend of Hindu and Islamic influences, unique for this region. The fort is surrounded by agricultural land and offers insights into medieval Odisha history.', 'Seranga, Ganjam, Odisha', 'Odisha', 'Fort', 19.5500, 84.7500, false, ARRAY['Medieval fort of Seranga chieftains','Blend of Hindu and Islamic architectural influences','Ruins of palaces, temples, and granaries','Important for understanding medieval Odisha history','Surrounded by scenic agricultural landscape'], '28 km', 'berhampur'),

('Bateswar Temple', 'An ancient temple complex featuring multiple small shrines dedicated to Lord Shiva. The temples display classical Odishan architecture with beautifully carved vimanas (temple towers). Archaeological surveys have dated these structures to the 7th-8th century CE, making them among the oldest surviving temples in the Ganjam district. The tranquil setting amidst mango groves adds to the charm.', 'Bateswar, Ganjam, Odisha', 'Odisha', 'Temple', 19.4500, 84.8200, false, ARRAY['Multiple ancient shrines from 7th-8th century CE','Classical Odishan architecture with carved vimanas','Among the oldest surviving temples in Ganjam','Tranquil setting amidst mango groves','Important archaeological heritage site'], '20 km', 'berhampur'),

('Maa Budhi Thakurani Temple', 'The presiding deity temple of Berhampur city, Maa Budhi Thakurani is one of the most important cultural institutions of southern Odisha. The biennial Thakurani Yatra is the largest cultural festival of the region, featuring elaborate processions, traditional music, and theatrical performances lasting 21 days. The temple represents the deep-rooted Shakti worship tradition of the region.', 'Berhampur, Ganjam, Odisha', 'Odisha', 'Temple', 19.3120, 84.7950, true, ARRAY['Presiding deity of Berhampur city','Biennial Thakurani Yatra lasts 21 days','Largest cultural festival of southern Odisha','Deep-rooted Shakti worship tradition','Elaborate processions with traditional music and theatre'], '0 km', 'berhampur'),

('Gandahati Waterfall', 'A magnificent waterfall hidden in the dense forests of the Eastern Ghats, Gandahati cascades from a height of about 60 meters. The surrounding forest is home to tribal communities who maintain traditional ways of life. The trek to the waterfall passes through bamboo groves and sal forests, offering encounters with diverse wildlife. A natural pool at the base is perfect for swimming.', 'Gajapati, Odisha', 'Odisha', 'Waterfall', 19.2200, 84.2500, false, ARRAY['Cascades from about 60 meters height','Surrounded by dense Eastern Ghat forests','Home to traditional tribal communities','Natural swimming pool at the base','Trek through bamboo groves and sal forests'], '75 km', 'berhampur'),

('Mahendragiri Hills', 'The second highest peak of Odisha at 1,501 meters, Mahendragiri is steeped in mythology and natural beauty. According to the Ramayana, it was part of the mountain Hanuman carried. The peak houses ancient temples, rare orchids, medicinal plants, and endemic species. The Eastern Ghats Biosphere Reserve here is home to diverse tribal cultures. Trekking to the summit offers views extending to the Bay of Bengal.', 'Mahendragiri, Gajapati, Odisha', 'Odisha', 'Hill', 18.9800, 84.3300, true, ARRAY['Second highest peak in Odisha at 1,501 meters','Connected to Ramayana legends of Hanuman','Home to rare orchids and medicinal plants','Part of Eastern Ghats Biosphere Reserve','Views extend to Bay of Bengal from summit'], '90 km', 'berhampur'),

('Desia Art Village', 'A unique cultural village showcasing the traditional art, craft, and lifestyle of the Desia tribal community. Visitors can experience traditional dance performances, handloom weaving, bamboo craft, and tribal cuisine. The village preserves centuries-old artistic traditions and offers immersive cultural experiences. It serves as a living museum of tribal heritage.', 'Gajapati, Odisha', 'Odisha', 'Cultural Site', 19.1800, 84.3800, false, ARRAY['Showcases Desia tribal art and culture','Traditional dance and handloom weaving demonstrations','Bamboo craft workshops available','Authentic tribal cuisine experiences','Living museum of tribal heritage'], '80 km', 'berhampur'),

('Srikurmam Temple', 'One of the only three temples in India dedicated to Lord Vishnu in the Kurma (tortoise) avatar. This ancient temple dates back to the 2nd century and features remarkable Chalukya and Eastern Ganga dynasty architecture. The temple''s inner sanctum houses a unique tortoise-shaped deity carved from a single stone. The annual Chandanotsava festival is a major draw.', 'Srikurmam, Srikakulam, near Ganjam border', 'Odisha', 'Temple', 18.2700, 83.8600, false, ARRAY['One of only three Kurma avatar temples in India','Dates back to the 2nd century','Chalukya and Eastern Ganga dynasty architecture','Unique tortoise-shaped deity from single stone','Annual Chandanotsava festival is major attraction'], '95 km', 'berhampur'),

('Laxmipur Beach', 'An untouched beach stretch near Berhampur offering raw coastal beauty. The beach is known for its black sand patches, casuarina plantations, and fishing villages. Local fishermen use traditional catamarans and nets, providing a glimpse into the maritime heritage of coastal Odisha. The beach is an emerging eco-tourism destination with minimal infrastructure.', 'Laxmipur, Ganjam, Odisha', 'Odisha', 'Beach', 19.2900, 84.9100, false, ARRAY['Untouched beach with raw coastal beauty','Black sand patches and casuarina plantations','Traditional fishing communities using catamarans','Emerging eco-tourism destination','Glimpse into maritime heritage of coastal Odisha'], '18 km', 'berhampur'),

('Maa Ghanteshwari Temple', 'A hilltop temple dedicated to Goddess Ghanteshwari, known for the melodious sound of temple bells echoing through the valleys. The temple sits at the convergence of two streams and is surrounded by dense forest. The annual festival draws thousands of tribal and non-tribal devotees. The temple is believed to grant wishes and is considered very powerful.', 'Ganjam, Odisha', 'Odisha', 'Temple', 19.4800, 84.6200, false, ARRAY['Hilltop temple with echoing bell sounds','Located at convergence of two streams','Surrounded by dense forest','Annual festival draws thousands of devotees','Believed to be especially powerful for granting wishes'], '35 km', 'berhampur'),

('Siddheshwar Temple', 'An important Shaivite temple in Berhampur featuring classical Odishan temple architecture. The temple is known for its elaborately carved entrance and the peaceful inner courtyard. Regular pujas and religious ceremonies maintain its spiritual vibrancy. The temple complex includes a sacred tank and multiple subsidiary shrines.', 'Berhampur, Ganjam, Odisha', 'Odisha', 'Temple', 19.3180, 84.7880, false, ARRAY['Important Shaivite temple in Berhampur','Classical Odishan architecture','Elaborately carved entrance gateway','Sacred tank within the temple complex','Multiple subsidiary shrines in the complex'], '1 km', 'berhampur'),

('Sonapur Beach', 'Named for its golden sand, Sonapur Beach is an emerging tourist destination along the southern Odisha coast. The beach stretches for several kilometers with clean, wide sands and moderate waves. Rocky outcrops at either end create sheltered coves. The nearby fishing village offers fresh seafood, and the area is being developed as an eco-tourism hub.', 'Sonapur, Ganjam, Odisha', 'Odisha', 'Beach', 19.2400, 84.9300, false, ARRAY['Named for its golden sand color','Several kilometer stretch of clean wide beach','Rocky outcrops create sheltered coves','Fresh seafood from nearby fishing village','Emerging eco-tourism destination'], '20 km', 'berhampur'),

('Raghunath Jew Temple', 'A significant Vaishnavite temple in Berhampur dedicated to Lord Rama. The temple is known for its beautiful Rath Yatra celebrations and traditional Odissi music performances during festivals. The architecture combines traditional Odishan and colonial influences, reflecting the temple''s historical evolution. The temple campus serves as a cultural center for the community.', 'Berhampur, Ganjam, Odisha', 'Odisha', 'Temple', 19.3100, 84.7920, false, ARRAY['Significant Vaishnavite temple dedicated to Lord Rama','Beautiful Rath Yatra celebrations','Traditional Odissi music during festivals','Architecture combines Odishan and colonial styles','Community cultural center'], '0 km', 'berhampur'),

('Daringbadi Hill Station', 'Known as the Kashmir of Odisha, Daringbadi is a hill station at an altitude of 3,000 feet in the Eastern Ghats. It is the only place in Odisha that experiences snowfall. The area features pine forests, coffee plantations, waterfalls, and tribal villages. Doluri River valley, Lover''s Point, and the Hill View Park are major attractions. The cool climate offers respite from coastal heat.', 'Daringbadi, Kandhamal, Odisha', 'Odisha', 'Hill Station', 19.8200, 84.1300, true, ARRAY['Known as the Kashmir of Odisha','Only place in Odisha that experiences snowfall','Located at 3,000 feet altitude','Features pine forests and coffee plantations','Cool climate with multiple waterfalls'], '95 km', 'berhampur'),

('Padmapani Temple', 'An ancient temple showcasing Buddhist-Hindu syncretic traditions, featuring exquisite stone carvings of Padmapani (Avalokiteshvara). The temple reflects the historical coexistence of Buddhist and Hindu traditions in this region. The carvings are considered masterpieces of early medieval sculpture. The peaceful surroundings make it an ideal spot for meditation and reflection.', 'Ganjam, Odisha', 'Odisha', 'Temple', 19.4300, 84.8100, false, ARRAY['Buddhist-Hindu syncretic temple','Exquisite stone carvings of Padmapani','Masterpieces of early medieval sculpture','Reflects historical Buddhist-Hindu coexistence','Peaceful setting for meditation'], '22 km', 'berhampur'),

('Gokuldham Temple', 'A modern temple complex dedicated to Lord Krishna in Berhampur. The temple features colorful depictions of Krishna''s life, well-maintained gardens, and a peaceful atmosphere. It has become a popular spiritual and community gathering spot. The temple hosts regular bhajan sessions and celebrations during Janmashtami and Holi with great enthusiasm.', 'Berhampur, Ganjam, Odisha', 'Odisha', 'Temple', 19.3150, 84.7960, false, ARRAY['Modern Krishna temple complex','Colorful depictions of Krishna''s life','Well-maintained gardens and peaceful atmosphere','Regular bhajan sessions','Grand Janmashtami and Holi celebrations'], '1 km', 'berhampur'),

('Surangi Waterfall', 'A picturesque waterfall located in the Gajapati district, Surangi Falls cascades through a narrow gorge surrounded by tropical forests. The waterfall is especially spectacular during the monsoon months when the water volume increases dramatically. The trek to reach the falls passes through tribal hamlets and offers encounters with diverse bird species. A hidden gem for adventure seekers.', 'Gajapati, Odisha', 'Odisha', 'Waterfall', 19.1500, 84.2800, false, ARRAY['Picturesque waterfall in narrow gorge','Spectacular during monsoon months','Trek passes through tribal hamlets','Diverse bird species along the trail','Hidden gem for adventure seekers'], '85 km', 'berhampur'),

('Narendrapur Sasan', 'A historical Jain pilgrimage site with ancient cave temples and rock-cut sculptures. The site contains inscriptions dating back to the 1st century BCE, making it one of the oldest Jain heritage sites in eastern India. The rock-cut elephant figures and standing Tirthankara sculptures are remarkable examples of early Indian art.', 'Narendrapur, Ganjam, Odisha', 'Odisha', 'Cave', 19.4800, 84.9200, false, ARRAY['Ancient Jain pilgrimage site','Cave temples from 1st century BCE','One of oldest Jain sites in eastern India','Rock-cut elephant figures and Tirthankara sculptures','Important examples of early Indian art'], '25 km', 'berhampur'),

('Berhampur Silk Weaving Center', 'The renowned Berhampur silk sarees are famous across India for their distinctive designs and superior quality. The weaving center showcases the traditional ikat and tie-dye techniques used to create these masterpieces. Visitors can watch artisans at work on handlooms, creating intricate patterns passed down through generations. The center also has a showroom for purchasing authentic Berhampur silks.', 'Berhampur, Ganjam, Odisha', 'Odisha', 'Cultural Site', 19.3100, 84.7850, false, ARRAY['Berhampur silk sarees famous across India','Traditional ikat and tie-dye techniques','Watch artisans work on handlooms','Patterns passed down through generations','Showroom for authentic Berhampur silks'], '0 km', 'berhampur'),

('Kuanl Jhari Waterfall', 'A hidden waterfall deep in the Eastern Ghats forest, Kuanl Jhari is a paradise for trekkers and nature lovers. The waterfall drops about 30 meters into a natural pool surrounded by moss-covered rocks. The surrounding forest is rich in medicinal herbs used by local tribal healers. The remote location means fewer crowds and a more intimate nature experience.', 'Eastern Ghats, Ganjam, Odisha', 'Odisha', 'Waterfall', 19.3800, 84.4500, false, ARRAY['Hidden waterfall in Eastern Ghats forest','30-meter drop into natural pool','Moss-covered rocks surround the pool','Forest rich in medicinal herbs','Remote location with fewer crowds'], '60 km', 'berhampur'),

('Samangala Fort', 'An ancient hilltop fortification associated with the legendary warrior kings of Kalinga. The fort ruins include stone walls, ramparts, and the remains of a palace complex. Archaeological evidence suggests the fort was active from the 3rd century BCE through the medieval period. The hilltop offers 360-degree panoramic views of the surrounding landscape.', 'Ganjam, Odisha', 'Odisha', 'Fort', 19.4200, 84.7600, false, ARRAY['Associated with warrior kings of Kalinga','Stone walls and ramparts still visible','Active from 3rd century BCE to medieval period','360-degree panoramic views from hilltop','Important archaeological significance'], '20 km', 'berhampur'),

('Kodala Jagannath Temple', 'A significant temple dedicated to Lord Jagannath in the Ganjam district, following the traditions of the famous Puri Jagannath Temple. The temple celebrates its own Rath Yatra with three beautifully decorated chariots. The annual car festival is the biggest event in the Kodala area, drawing devotees from surrounding districts. The temple architecture is a smaller replica of the Puri temple.', 'Kodala, Ganjam, Odisha', 'Odisha', 'Temple', 19.6200, 84.9400, false, ARRAY['Follows traditions of Puri Jagannath Temple','Own Rath Yatra with three decorated chariots','Biggest annual event in Kodala area','Architecture replicates Puri temple style','Draws devotees from surrounding districts'], '40 km', 'berhampur'),

('Sana Jhada Peetha', 'A revered tantric shrine located in a dense forest, associated with powerful spiritual practices. The shrine features an ancient banyan tree under which rituals have been performed for centuries. Local devotees believe the site possesses extraordinary spiritual energy. The forest setting adds to the mystical atmosphere of this unique pilgrimage destination.', 'Ganjam, Odisha', 'Odisha', 'Temple', 19.3900, 84.7300, false, ARRAY['Revered tantric shrine in dense forest','Ancient banyan tree at the center','Centuries of ritual practice at this site','Believed to possess extraordinary spiritual energy','Mystical forest atmosphere'], '15 km', 'berhampur'),

-- BHUBANESWAR AREA MONUMENTS (55+ places)
('Lingaraja Temple', 'The largest and most prominent temple in Bhubaneswar, Lingaraja Temple is a masterpiece of Kalinga architecture dating back to the 11th century. The 180-feet tall deul (tower) dominates the city skyline. The temple complex contains over 100 subsidiary shrines within its massive compound walls. The temple is dedicated to Harihara, a combined form of Shiva and Vishnu, representing the unique syncretism of Odisha.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2382, 85.8344, true, ARRAY['Largest temple in Bhubaneswar at 180 feet tall','Masterpiece of 11th century Kalinga architecture','Over 100 subsidiary shrines in the complex','Dedicated to Harihara (Shiva-Vishnu combined)','Non-Hindus can view from a raised platform outside'], '350 km', 'bhubaneswar'),

('Konark Sun Temple', 'A UNESCO World Heritage Site built in the 13th century by King Narasimhadeva I, the Sun Temple at Konark is designed as a colossal chariot of the Sun God with 24 elaborately carved stone wheels and seven horses. The temple is renowned for its exquisite stone carvings depicting every aspect of medieval life. The annual Konark Dance Festival celebrates classical dance forms against this magnificent backdrop.', 'Konark, Puri, Odisha', 'Odisha', 'Temple', 19.8876, 86.0945, true, ARRAY['UNESCO World Heritage Site since 1984','Built in 13th century as a colossal chariot','24 elaborately carved stone wheels serve as sundials','Exquisite erotic and celestial carvings','Annual Konark Dance Festival held here'], '380 km', 'bhubaneswar'),

('Udayagiri & Khandagiri Caves', 'Ancient Jain rock-cut caves dating back to the 2nd century BCE, commissioned by Emperor Kharavela of the Chedi dynasty. The 33 caves (18 on Udayagiri, 15 on Khandagiri) feature intricate carvings depicting court scenes, processions, and religious symbols. Hathi Gumpha (Elephant Cave) contains the famous inscription of King Kharavela, one of the most important historical documents in Indian history.', 'Bhubaneswar, Odisha', 'Odisha', 'Cave', 20.2553, 85.7829, true, ARRAY['Dating back to 2nd century BCE','Commissioned by Emperor Kharavela','33 rock-cut caves across two hills','Hathi Gumpha inscription is historically invaluable','Depicts court scenes and religious ceremonies'], '350 km', 'bhubaneswar'),

('Mukteshwar Temple', 'Often called the Gem of Odishan Architecture, Mukteshwar Temple dates to the 10th century. Its most distinctive feature is the ornate torana (arched gateway), the only one of its kind in Odisha. The temple showcases the evolution from early to mature Kalinga style with its exquisitely carved figures of female ascetics, Nagas, and celestial musicians. Every surface is adorned with intricate geometric and floral patterns.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2438, 85.8380, true, ARRAY['Called the Gem of Odishan Architecture','10th century temple with unique torana gateway','Only arched gateway of its kind in Odisha','Exquisitely carved female ascetics and Nagas','Showcases evolution of Kalinga architectural style'], '350 km', 'bhubaneswar'),

('Rajarani Temple', 'A beautifully ornate 11th century temple famous for its stunning sculptures of the eight directional guardian deities (Ashta Dikpalas) and graceful female figures in various poses. The temple gets its name from the local sandstone called Rajarani. Unlike most Bhubaneswar temples, it has no presiding deity, suggesting it may never have been consecrated. The red and gold sandstone gives the temple a warm, glowing appearance.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2450, 85.8433, true, ARRAY['11th century temple with stunning sculptures','Named after the local Rajarani sandstone','No presiding deity - may never have been consecrated','Beautiful Ashta Dikpala guardian deity carvings','Red and gold sandstone gives warm glow'], '350 km', 'bhubaneswar'),

('Dhauli Peace Pagoda (Shanti Stupa)', 'Built jointly by Japan and India, the white Peace Pagoda at Dhauli sits atop the hill where Emperor Ashoka fought the bloody Kalinga War in 261 BCE. This battle transformed Ashoka from a ruthless conqueror to a champion of peace and Buddhism. The Dhauli rock edicts here are among the oldest stone-carved edicts in India. The panoramic view from the stupa encompasses the ancient battlefield stretching to the Daya River.', 'Dhauli, Bhubaneswar, Odisha', 'Odisha', 'Stupa', 20.2030, 85.8560, true, ARRAY['Site of the pivotal Kalinga War of 261 BCE','Transformed Emperor Ashoka to embrace Buddhism','Indo-Japanese Peace Pagoda built in 1972','Among the oldest rock-carved edicts in India','Panoramic views of the ancient Kalinga battlefield'], '348 km', 'bhubaneswar'),

('Nandankanan Zoological Park', 'One of India''s premier zoos and botanical gardens, Nandankanan spans 437 hectares and is famous for its white tiger breeding program. The zoo houses over 170 species of animals in natural habitats. The Botanical Garden within features over 1,000 species of plants including rare orchids. The zoo also operates a toy train, safari, and boating facilities in Kanjia Lake.', 'Bhubaneswar, Odisha', 'Odisha', 'Park', 20.3953, 85.8233, true, ARRAY['One of India''s premier zoos spanning 437 hectares','Famous white tiger breeding program','Over 170 species of animals in natural habitats','Botanical garden with 1,000+ plant species','Safari, toy train, and boating in Kanjia Lake'], '350 km', 'bhubaneswar'),

('Parasurameswara Temple', 'Dating back to the 7th century CE, Parasurameswara Temple is one of the oldest and best-preserved temples in Bhubaneswar. The temple is a perfect example of early Kalinga architecture with its richly carved exterior panels depicting Shiva as Nataraja, Ardhanarisvara, and other forms. The latticed windows and elephant procession friezes are particularly noteworthy. It stands as a complete example of the deul-jagamohana architectural style.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2425, 85.8400, true, ARRAY['One of Bhubaneswar''s oldest temples from 7th century','Best-preserved early Kalinga architecture','Richly carved panels of Shiva as Nataraja','Notable latticed windows and elephant friezes','Complete deul-jagamohana architectural example'], '350 km', 'bhubaneswar'),

('Odisha State Museum', 'Established in 1938, the Odisha State Museum houses an impressive collection spanning archaeology, natural history, art, armory, and manuscripts. The museum displays stone sculptures from Bhubaneswar''s ancient temples, palm leaf manuscripts, tribal artifacts, and weapons from various periods. The numismatic collection features coins from the Mauryan to British period, tracing 2,500 years of monetary history.', 'Bhubaneswar, Odisha', 'Odisha', 'Museum', 20.2682, 85.8410, false, ARRAY['Established in 1938 with rich collections','Stone sculptures from ancient temples','Palm leaf manuscripts and tribal artifacts','Numismatic collection spanning 2,500 years','Covers archaeology, natural history, art, and armory'], '350 km', 'bhubaneswar'),

('Brahmeshwara Temple', 'An exquisitely carved 9th century Shiva temple known for its finely detailed sculptural panels. The temple introduces the pancha-ratha style to Bhubaneswar temple architecture. The exterior walls feature beautifully carved figures of deities, celestial beings, amorous couples, and mythological scenes. The temple''s unique feature is the intricate chain and bell motif running across the facade.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2420, 85.8370, false, ARRAY['9th century Shiva temple','Introduces pancha-ratha architectural style','Finely detailed sculptural panels','Unique chain and bell motif on facade','Beautiful carvings of celestial beings and couples'], '350 km', 'bhubaneswar'),

('Bindu Sagar Lake', 'The sacred lake at the heart of Bhubaneswar''s old town, Bindu Sagar is believed to contain drops of water from every sacred stream in India. The lake is surrounded by numerous ancient temples and forms the center of the city''s Temple Zone. During the annual Ashokastami festival, the presiding deity of Lingaraja Temple is brought here for a ceremonial bath. The lake offers serene views of the temple skyline.', 'Bhubaneswar, Odisha', 'Odisha', 'Lake', 20.2400, 85.8350, false, ARRAY['Sacred lake at the heart of old Bhubaneswar','Believed to contain drops from every sacred stream in India','Surrounded by numerous ancient temples','Ashokastami festival ceremony held here','Serene views of temple-studded skyline'], '350 km', 'bhubaneswar'),

('ISKCON Temple Bhubaneswar', 'The magnificent ISKCON temple in Bhubaneswar is dedicated to Sri Sri Radha Krishna Chandra. The temple complex features stunning architecture combining traditional and modern elements, lush gardens, a museum, and a large auditorium. The temple serves free vegetarian meals daily and hosts major festivals like Janmashtami and Ratha Yatra with great grandeur. It''s also a center for Vedic education and meditation.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2950, 85.8200, false, ARRAY['Dedicated to Sri Sri Radha Krishna Chandra','Stunning blend of traditional and modern architecture','Free vegetarian meals served daily','Major festivals celebrated with grandeur','Center for Vedic education and meditation'], '350 km', 'bhubaneswar'),

('Ram Mandir Bhubaneswar', 'A prominent Hindu temple in the heart of Bhubaneswar, Ram Mandir is dedicated to Lord Rama and is one of the city''s most visited temples. The temple features traditional Odishan architecture with beautiful wall carvings and a spacious prayer hall. The temple complex includes gardens and cultural spaces. Ram Navami celebrations here are among the most elaborate in the city.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2700, 85.8400, false, ARRAY['Prominent temple in heart of Bhubaneswar','Dedicated to Lord Rama','Traditional Odishan architecture with wall carvings','Ram Navami celebrations are elaborate','Spacious prayer hall and gardens'], '350 km', 'bhubaneswar'),

('Ratnagiri Buddhist Monastery', 'One of the three hilltop Buddhist heritage sites in the Diamond Triangle of Odisha, Ratnagiri was a major Mahayana Buddhist center from the 5th to 12th century. Excavations revealed a massive monastery, beautiful sculptures, and a stunning stone gateway. The site museum houses exquisite bronze and stone Buddha images, ornate door frames, and carved bricks. The hill offers beautiful views of the Brahmani River valley.', 'Ratnagiri, Jajpur, Odisha', 'Odisha', 'Monastery', 20.6200, 86.3400, true, ARRAY['Major Mahayana Buddhist center from 5th-12th century','Part of Diamond Triangle of Buddhist sites','Stunning stone gateway and monastery ruins','Exquisite bronze and stone Buddha images','Beautiful views of Brahmani River valley'], '370 km', 'bhubaneswar'),

('Lalitgiri Buddhist Complex', 'The earliest Buddhist site in the Diamond Triangle, Lalitgiri dates back to the 1st century CE. Excavations uncovered a brick monastery, sculptured panels, and notably a stone relic casket containing actual bone relics believed to be of Buddha. The hilltop stupa and monastery ruins sit amidst green hills, offering a peaceful pilgrimage experience. The site museum showcases remarkable Buddhist antiquities.', 'Lalitgiri, Cuttack, Odisha', 'Odisha', 'Monastery', 20.6500, 86.2800, false, ARRAY['Earliest Buddhist site in Diamond Triangle from 1st century CE','Stone casket with bone relics believed to be of Buddha','Brick monastery and sculptured panels','Hilltop stupa with green hill surroundings','Museum with remarkable Buddhist antiquities'], '370 km', 'bhubaneswar'),

('Tribal Museum Bhubaneswar', 'The Museum of Tribal Arts and Artifacts showcases the rich cultural heritage of Odisha''s 62 tribal communities, which constitute nearly 23% of the state''s population. Displays include traditional costumes, jewelry, weapons, musical instruments, and models of tribal dwellings. The museum provides insights into the diverse customs, rituals, and art forms of communities like Kondh, Saora, Bonda, and Dongria.', 'Bhubaneswar, Odisha', 'Odisha', 'Museum', 20.2850, 85.8100, false, ARRAY['Showcases 62 tribal communities of Odisha','Tribal communities form 23% of state population','Traditional costumes, jewelry, and weapons displayed','Models of tribal dwellings and lifestyle','Insights into Kondh, Saora, Bonda, Dongria cultures'], '350 km', 'bhubaneswar'),

('Ekamra Kanan Botanical Gardens', 'A 217-acre botanical garden and park in Bhubaneswar featuring diverse collections of tropical and sub-tropical plants. The garden includes a rose garden with over 200 varieties, a cactus house, orchid collection, and medicinal plant section. The Japanese Garden within is a peaceful oasis with zen elements. The park also features a musical fountain that operates in the evenings with synchronized light shows.', 'Bhubaneswar, Odisha', 'Odisha', 'Park', 20.3300, 85.8200, false, ARRAY['217-acre botanical garden and park','Rose garden with over 200 varieties','Japanese Garden with zen elements','Musical fountain with evening light shows','Cactus house, orchid, and medicinal plant collections'], '350 km', 'bhubaneswar'),

('Dhauligiri Hills Peace Park', 'The expanded peace park around the Dhauli Stupa includes beautifully landscaped gardens, the ancient rock-cut elephant sculpture (India''s earliest rock-cut sculpture), and meditation halls. The park commemorates the transformation of warfare to peace after the Kalinga War. Evening light and sound shows narrate the story of Emperor Ashoka''s transformation. The park is a UNESCO tentative list site.', 'Dhauli, Bhubaneswar, Odisha', 'Odisha', 'Park', 20.2040, 85.8550, false, ARRAY['Beautifully landscaped peace park','India''s earliest rock-cut elephant sculpture','Commemorates Kalinga War transformation','Evening light and sound shows','UNESCO tentative list site'], '348 km', 'bhubaneswar'),

('Kedar Gouri Temple', 'An ancient twin temple complex dedicated to Lord Shiva (Kedar) and Goddess Parvati (Gouri), dating to the 8th century. The temple pair represents the divine marriage of Shiva and Parvati. The carvings showcase transitional Kalinga architecture between early and mature styles. The temple is considered auspicious for marriage ceremonies and is visited by newly married couples.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2430, 85.8360, false, ARRAY['8th century twin temple complex','Dedicated to Lord Shiva and Goddess Parvati','Represents divine marriage of Shiva-Parvati','Transitional Kalinga architecture','Auspicious for marriage ceremonies'], '350 km', 'bhubaneswar'),

('Pathani Samanta Planetarium', 'Named after the legendary astronomer Pathani Samanta, this is one of the largest planetariums in eastern India. The planetarium features a modern projection system showing celestial phenomena, astronomical shows, and 3D documentaries about space exploration. Interactive exhibits about the solar system, galaxies, and black holes make it educational and entertaining for visitors of all ages.', 'Bhubaneswar, Odisha', 'Odisha', 'Museum', 20.2600, 85.8350, false, ARRAY['One of largest planetariums in eastern India','Named after astronomer Pathani Samanta','Modern projection system for celestial shows','Interactive exhibits about solar system and galaxies','3D documentaries about space exploration'], '350 km', 'bhubaneswar'),

('Nicco Park & World', 'An amusement and water park offering entertainment for families. Features include roller coasters, water slides, boating, go-karting, and various thrill rides. The park also has a food court, souvenir shops, and regular cultural shows. It''s one of the most popular recreational destinations in Bhubaneswar for weekend outings.', 'Bhubaneswar, Odisha', 'Odisha', 'Park', 20.3100, 85.8200, false, ARRAY['Popular amusement and water park','Roller coasters, water slides, and go-karting','Family entertainment with thrill rides','Food court and souvenir shops','Cultural shows and weekend entertainment'], '350 km', 'bhubaneswar'),

('Ananta Vasudeva Temple', 'The only temple in Bhubaneswar dedicated to Lord Vishnu (Krishna), built in the 13th century. The temple follows the traditional Kalinga architectural style and is known for its elaborate rituals and prasad offerings similar to the Jagannath Temple in Puri. The temple kitchen prepares 56 varieties of bhog (food offerings) daily. It''s an important site for understanding Vaishnavite traditions in Odisha.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2395, 85.8350, false, ARRAY['Only Vishnu temple in Bhubaneswar','Built in 13th century Kalinga style','56 varieties of bhog prepared daily','Rituals similar to Puri Jagannath Temple','Important for understanding Vaishnavite traditions'], '350 km', 'bhubaneswar'),

('Sisireswara Temple', 'An 8th-century Shaivite temple known for its well-preserved carvings and architectural details. The temple stands near Bindu Sagar Lake and features beautiful carved panels depicting mythological scenes. The temple''s compact form represents the early phase of Kalinga temple architecture, making it important for studying the evolution of temple design in Bhubaneswar.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2410, 85.8355, false, ARRAY['Well-preserved 8th century Shaivite temple','Near Bindu Sagar Lake','Beautiful carved mythological panels','Early phase Kalinga architecture','Important for temple design evolution study'], '350 km', 'bhubaneswar'),

('Khandagiri Jain Temples', 'Modern Jain temples built atop Khandagiri Hill alongside the ancient caves. The temples feature beautiful white marble architecture with colorful murals depicting Jain Tirthankaras. The hilltop location offers panoramic views of Bhubaneswar city. The annual Mahamastakabhisheka ceremony attracts Jain pilgrims from across India. The combination of ancient caves and modern temples creates a unique spiritual landscape.', 'Khandagiri, Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2560, 85.7830, false, ARRAY['Modern Jain temples atop ancient hill','White marble architecture with colorful murals','Panoramic views of Bhubaneswar city','Annual Mahamastakabhisheka ceremony','Unique blend of ancient caves and modern temples'], '350 km', 'bhubaneswar'),

('Chandaka Elephant Sanctuary', 'A 175 sq km sanctuary established to protect the Asiatic elephants and their habitat on the outskirts of Bhubaneswar. The sanctuary is home to over 60 elephants along with leopards, deer, wild boar, and numerous bird species. Nature trails and watchtowers allow visitors to observe wildlife in natural settings. The sanctuary plays a crucial role in elephant conservation in urban-adjacent forests.', 'Chandaka, Bhubaneswar, Odisha', 'Odisha', 'Sanctuary', 20.3700, 85.7200, false, ARRAY['175 sq km elephant sanctuary','Home to over 60 Asiatic elephants','Also has leopards, deer, and wild boar','Nature trails and watchtowers for visitors','Crucial for urban-adjacent elephant conservation'], '355 km', 'bhubaneswar'),

('Puri Jagannath Temple', 'One of the Char Dham pilgrimage sites, the 12th-century Jagannath Temple in Puri is one of the most sacred Hindu temples in India. The massive temple complex, with its 65-meter-high tower, dominates the Puri skyline. The annual Rath Yatra (Car Festival) is world-famous, with millions participating. The temple''s Mahaprasad is prepared in the world''s largest kitchen, serving 100,000 people daily.', 'Puri, Odisha', 'Odisha', 'Temple', 19.8048, 85.8182, true, ARRAY['One of the four Char Dham sites','12th century temple with 65-meter tower','Annual Rath Yatra is world famous','World''s largest kitchen serves 100,000 daily','Non-Hindus cannot enter the main temple'], '380 km', 'bhubaneswar'),

('Puri Beach', 'One of India''s most famous beaches, Puri Beach stretches along the Bay of Bengal offering golden sands, rolling waves, and spectacular sunrises. The beach is dotted with colorful fishing boats and hosts the annual Puri Beach Festival featuring sand art competitions, cultural performances, and food fairs. The beach is also known for the international sand art festival where master artists create intricate sculptures.', 'Puri, Odisha', 'Odisha', 'Beach', 19.7981, 85.8315, true, ARRAY['One of India''s most famous beaches','Annual Beach Festival with sand art competitions','International sand art festival destination','Colorful fishing boats along the shore','Spectacular sunrise views over Bay of Bengal'], '380 km', 'bhubaneswar'),

('Pipili Applique Village', 'Famous for its vibrant applique craft, Pipili is India''s most renowned applique craft village. The colorful umbrellas, wall hangings, lamp shades, and decorative items made here are used in the Puri Jagannath Temple''s Rath Yatra. The craft involves stitching cut pieces of colorful cloth onto a base to create intricate patterns. Walking through the craft shops lining the main road is a kaleidoscopic experience.', 'Pipili, Puri, Odisha', 'Odisha', 'Cultural Site', 20.1200, 85.8300, false, ARRAY['India''s most famous applique craft village','Crafts used in Puri Rath Yatra chariots','Colorful umbrellas, wall hangings, and lamp shades','Traditional art of stitching cloth patterns','Kaleidoscopic craft shops along main road'], '370 km', 'bhubaneswar'),

('Raghurajpur Heritage Village', 'A living art village where every household practices the traditional Pattachitra art form. This 700-year-old art involves painting intricate mythological narratives on specially prepared cloth or palm leaves using natural colors. The village also produces tussar paintings, stone carvings, and papier-mâché masks. UNESCO has recognized Raghurajpur as a heritage craft village, preserving one of India''s finest art traditions.', 'Raghurajpur, Puri, Odisha', 'Odisha', 'Cultural Site', 19.8900, 85.8500, false, ARRAY['Every household practices Pattachitra art','700-year-old traditional painting art form','Uses natural colors on cloth and palm leaves','UNESCO recognized heritage craft village','Also produces tussar paintings and stone carvings'], '375 km', 'bhubaneswar'),

('Satkosia Gorge', 'A dramatic gorge where the Mahanadi River cuts through the Eastern Ghats, creating a 22-km long canyon with steep rocky walls rising 200 meters on both sides. The Satkosia Tiger Reserve surrounding the gorge shelters tigers, gharials, mugger crocodiles, and diverse bird species. River camping and crocodile spotting boat rides are popular activities. The gorge is at the meeting point of two distinct ecosystems.', 'Satkosia, Angul, Odisha', 'Odisha', 'Natural Wonder', 20.6700, 84.7900, true, ARRAY['22-km gorge with 200-meter rocky walls','Part of Satkosia Tiger Reserve','Home to tigers, gharials, and mugger crocodiles','River camping and boat rides available','Meeting point of two distinct ecosystems'], '360 km', 'bhubaneswar'),

('Bhitarkanika National Park', 'India''s second-largest mangrove ecosystem, Bhitarkanika is famous for its saltwater crocodile population, the largest in India. The park hosts the mass nesting of Olive Ridley turtles at Gahirmatha Beach. Over 215 bird species have been recorded here, including the rare white-bellied sea eagle. Boat safaris through mangrove channels offer encounters with monitor lizards, king cobras, and diverse aquatic life.', 'Bhitarkanika, Kendrapara, Odisha', 'Odisha', 'Sanctuary', 20.7200, 86.8700, false, ARRAY['India''s second-largest mangrove ecosystem','Largest saltwater crocodile population in India','Gahirmatha mass turtle nesting site','Over 215 bird species recorded','Boat safaris through mangrove channels'], '380 km', 'bhubaneswar'),

('Simlipal National Park', 'A 2,750 sq km national park and tiger reserve in the Mayurbhanj district, Simlipal is one of India''s most beautiful wilderness areas. It features dense sal and teak forests, spectacular waterfalls including Barehipani Falls (399m, India''s 2nd highest) and Joranda Falls (181m). The park is home to tigers, elephants, gaur, and the melanistic tiger (black tiger), found almost exclusively here.', 'Simlipal, Mayurbhanj, Odisha', 'Odisha', 'Sanctuary', 21.8300, 86.3300, false, ARRAY['2,750 sq km tiger reserve','Barehipani Falls is India''s 2nd highest at 399m','Home to the rare melanistic black tiger','Dense sal and teak forests','Elephants, gaur, and diverse wildlife'], '400 km', 'bhubaneswar'),

('Vaital Temple', 'An 8th-century tantric temple dedicated to Goddess Chamunda, the Vaital Temple is distinguished by its unusual double-storied wagon-roof (khakhara) design, unique in Bhubaneswar. The interior houses a fierce eight-armed image of Chamunda sitting on a corpse, surrounded by skulls. The exterior carvings include elaborate depictions of Durga slaying Mahishasura. It represents tantric worship traditions of medieval Odisha.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2440, 85.8352, false, ARRAY['8th century tantric temple','Unique khakhara (wagon-roof) design','Fierce eight-armed Chamunda image inside','Elaborate Durga Mahishasura carvings outside','Represents medieval tantric worship traditions'], '350 km', 'bhubaneswar'),

('Chausath Yogini Temple', 'One of the rare circular temples in India, the Chausath Yogini Temple at Hirapur dates to the 9th century. The open-air temple features 64 small niches housing yogini figures, each with a distinct pose and attribute. This is one of only four such temples in India. The temple is linked to tantric worship practices and represents an important facet of medieval Indian religious art.', 'Hirapur, Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2100, 85.8800, false, ARRAY['Rare circular temple from 9th century','64 niches with distinct yogini figures','One of only four such temples in India','Linked to tantric worship practices','Important medieval Indian religious art'], '355 km', 'bhubaneswar'),

('Biju Patnaik Museum of Technology', 'A science and technology museum named after the legendary leader Biju Patnaik. The museum features interactive exhibits on aerospace, space technology, renewable energy, and Information Technology. A replica of the Dakota aircraft flown by Biju Patnaik during Indonesia''s independence struggle is a highlight. The planetarium section hosts regular astronomy shows for students and visitors.', 'Bhubaneswar, Odisha', 'Odisha', 'Museum', 20.2750, 85.8300, false, ARRAY['Named after legendary leader Biju Patnaik','Interactive aerospace and space technology exhibits','Replica of Dakota aircraft from Indonesian freedom struggle','Renewable energy and IT sections','Regular astronomy shows in planetarium'], '350 km', 'bhubaneswar'),

('Mangalajodi Wetland', 'A critical wetland on the northern edge of Chilika Lake, Mangalajodi has transformed from a poaching hotspot to one of India''s best birdwatching destinations. Over 300,000 migratory birds from as far as Siberia, Central Asia, and Europe visit annually. Community-based ecotourism has made it a conservation success story. Early morning boat rides through the marshes offer unparalleled birdwatching experiences.', 'Mangalajodi, Khurda, Odisha', 'Odisha', 'Natural Wonder', 19.8500, 85.4500, false, ARRAY['Over 300,000 migratory birds visit annually','Birds from Siberia, Central Asia, and Europe','Transformed from poaching to conservation success','Community-based ecotourism model','Unparalleled early morning birdwatching'], '355 km', 'bhubaneswar'),

('Chudanga Temple Complex', 'A group of medieval temples dating from the Eastern Ganga dynasty period (12th-13th century). The temples showcase mature Kalinga architecture with elaborate carvings. The main temple features a tall shikhara and intricate relief work. The complex provides insights into the religious life and artistic achievements during the golden age of Odishan temple architecture.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2380, 85.8330, false, ARRAY['Medieval temples from Eastern Ganga period','12th-13th century Kalinga architecture','Elaborate carvings and tall shikhara','Insights into golden age religious life','Fine examples of mature Odishan temple art'], '350 km', 'bhubaneswar'),

('State Handicrafts Museum', 'Also known as the Museum of Handlooms, this museum showcases the exquisite textile heritage of Odisha including Sambalpuri, Bomkai, and Berhampur silks. Displays include traditional looms, weaving techniques, filigree silver work, dhokra metal craft, stone and wood carvings, and pattachitra paintings. The museum shop offers authentic handicraft purchases directly supporting artisan communities.', 'Bhubaneswar, Odisha', 'Odisha', 'Museum', 20.2680, 85.8400, false, ARRAY['Showcases Odisha''s textile heritage','Sambalpuri, Bomkai, and Berhampur silks','Traditional looms and weaving demonstrations','Dhokra, filigree, and pattachitra displays','Museum shop supporting artisan communities'], '350 km', 'bhubaneswar'),

('Kapilash Temple & Hills', 'A Shaivite pilgrimage site atop Kapilash Hill in Dhenkanal, featuring a temple dedicated to Lord Chandrasekhar (Shiva). The hill rises to 2,239 feet and the trek to the summit passes through dense forests. According to legend, sage Kapila meditated here. The temple area includes natural caves and provides spectacular views. The annual Shiva Ratri celebration draws lakhs of devotees.', 'Kapilash, Dhenkanal, Odisha', 'Odisha', 'Temple', 20.8400, 85.7500, false, ARRAY['Shaivite temple at 2,239 feet elevation','Legend of sage Kapila''s meditation','Trek through dense forests to summit','Natural caves in temple area','Shiva Ratri draws lakhs of devotees'], '370 km', 'bhubaneswar'),

('Assia Village Heritage Walk', 'A heritage walk through one of Bhubaneswar''s oldest neighborhoods, passing ancient temples, traditional Odisha-style houses, and community wells that have served residents for centuries. The walk reveals layers of living history from the 7th century onwards. Local guides share stories of traditions, festivals, and culinary heritage. Stone inscriptions found along the route date to various dynasties.', 'Old Town, Bhubaneswar, Odisha', 'Odisha', 'Cultural Site', 20.2400, 85.8340, false, ARRAY['Heritage walk through oldest neighborhood','Ancient temples and traditional Odisha houses','Community wells centuries old','Living history from 7th century onwards','Stone inscriptions from various dynasties'], '350 km', 'bhubaneswar'),

('Uttara Shiva Temple', 'A lesser-known but architecturally significant temple in Bhubaneswar''s old town area. The 9th century temple features finely carved figures and ornamental motifs characteristic of the middle phase of Kalinga temple architecture. The peaceful compound away from tourist crowds allows for unhurried appreciation of the stone craftsmanship that defines Bhubaneswar''s temple heritage.', 'Bhubaneswar, Odisha', 'Odisha', 'Temple', 20.2415, 85.8365, false, ARRAY['9th century temple in old town','Middle phase Kalinga architecture','Finely carved figures and ornamental motifs','Peaceful compound away from crowds','Excellent stone craftsmanship'], '350 km', 'bhubaneswar'),

('Saptasajya Hills', 'Seven interconnected hills steeped in Ramayana legend — Lord Rama is believed to have rested here during his exile. The hills feature ancient rock paintings, medicinal herb forests, and panoramic viewpoints. A natural spring and small temple make it a spiritual retreat. The hills are also home to several rare plant species and offer excellent trekking opportunities.', 'Dhenkanal, Odisha', 'Odisha', 'Hill', 20.7500, 85.6500, false, ARRAY['Seven interconnected hills from Ramayana legend','Lord Rama believed to have rested here','Ancient rock paintings','Medicinal herb forests','Natural spring and temple at the site'], '370 km', 'bhubaneswar'),

('Pradhanpat Waterfall', 'A stunning waterfall near Deogarh in western Odisha, Pradhanpat cascades from a height of 60 meters amidst pristine forest. The waterfall creates a misty ambiance perfect for nature photography. The surrounding area is dotted with tribal villages where traditional crafts and customs are still practiced. The best time to visit is during and immediately after the monsoon season.', 'Deogarh, Odisha', 'Odisha', 'Waterfall', 21.5200, 84.7500, false, ARRAY['60-meter waterfall in pristine forest','Misty ambiance perfect for photography','Surrounding tribal villages with living traditions','Best visited during and after monsoon','One of western Odisha''s natural gems'], '380 km', 'bhubaneswar'),

('Baleshwar Beach', 'The coastal stretch near Balasore in northern Odisha is known for its wide sandy beaches and fishing heritage. Chandipur Beach here is famous for its unique phenomenon of the sea receding up to 5 kilometers during low tide, allowing visitors to walk on the exposed seabed. The area is also significant as the site of India''s Integrated Test Range for missile testing.', 'Balasore, Odisha', 'Odisha', 'Beach', 21.5000, 87.0600, false, ARRAY['Sea recedes up to 5 km during low tide','Can walk on exposed seabed at Chandipur','Wide sandy beaches with fishing heritage','Site of India''s missile testing range','Unique tidal phenomenon in India'], '400 km', 'bhubaneswar');
